#pragma once

# define ORYX_CONFIGURATOR
# undef PERMISSIVE_HOLD
# undef COMBO_COUNT
# undef TAPPING_TERM
# define TAPPING_TERM 200
# define STARTUP_SONG SONG(COIN_SOUND)
//# define AUDIO_DAC_SAMPLE_MAX 4095U
# define AUDIO_DAC_SAMPLE_MAX 3276U
# define LEADER_TIMEOUT 300
# define LEADER_PER_KEY_TIMING
# define TAPPING_TOGGLE 1

# define MK_KINETIC_SPEED
# define MOUSEKEY_DELAY 0
# define MOUSEKEY_MOVE_DELTA 1
# define MOUSEKEY_INITIAL_SPEED 16
# define MOUSEKEY_BASE_SPEED 250
# define MOUSEKEY_ACCELERATED_SPEED 100
# define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 100
# define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 150

# define COMBO_MUST_TAP_PER_COMBO
